[package]
name = "passhley/flipbook"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.2"
roact-hooks = "kampfkarren/roact-hooks@0.3.0"
rodux = "roblox/rodux@3.0.0"
